export const BATTLE = 'BATTLE';
export const RECEIVE_BATTLE = 'RECEIVE_BATTLE';
export const BATTLE_ERROR = 'BATTLE_ERROR';

export const LIST_BATTLE = 'LIST_BATTLE';
export const RECEIVE_LIST_BATTLE = 'RECEIVE_LIST_BATTLE';
export const LIST_BATTLE_ERROR = 'LIST_BATTLE_ERROR';
